Tuning Kafka configurations for microservices
Service ETL was frequently failing with this error:
org.apache.kafka.clients.consumer.CommitFailedException: Offset commit
cannot be completed since the consumer is not part of an active group
for auto partition assignment; it is likely that the consumer was kicked
out of the group.